### ISSUE TITLE
Redactor to TinyMCE

### ISSUE THREAD

**Issue by wmdhosting** [ryssbowh/craft-activity#1]
I have latest version of everything. 

Changed Redactor field to  TinyMCE

and got this error. when i go to  acitvity page.. 
![Snag_af142bd](https://user-images.githubusercontent.com/76176291/197714452-3328d97a-7def-4af0-9e7a-59ee9daa2904.png)

**Comment by ryssbowh** [comment]
Thanks for reporting,
What's your Craft version ? Have you just updated to Craft 4.3 ?

**Comment by wmdhosting** [comment]
not. yet  just before 4.3..

**Comment by ryssbowh** [comment]
Thanks, found the issue, will release a fix soon

**Comment by ryssbowh** [comment]
This is out in 2.1.0.
I also added the tinyMCE field support at the same time

**Comment by wmdhosting** [comment]
ok thx :)

**Comment by wmdhosting** [comment]
Upgraded. no errors now :)

Just info..  this filters  where not working properly before nor after upgrade. 

Tested in Firefox and Chrome.. 
![Snag_10bc0e33](https://user-images.githubusercontent.com/76176291/198007144-eb59e1b3-fb62-40a2-bc9e-3638374bd4fb.png)

**Comment by wmdhosting** [comment]
found one more. error :)
![Snag_115a8c9a](https://user-images.githubusercontent.com/76176291/198041468-5a13bd2b-70e5-476a-adec-d0d4b16443f9.png)

**Comment by ryssbowh** [comment]
I fixed the filters in 2.1.1 just now.
I can't reproduce the Matrix problem though, do you have a reproducible scenario ?

**Comment by wmdhosting** [comment]
i got similar error once more. on saving  taht same entry. but  not getting allways 

<img width="445" alt="image1" src="https://user-images.githubusercontent.com/76176291/198515075-4b179db6-5222-48ee-a518-f4b957320577.png">

**Comment by wmdhosting** [comment]
i got one more.. 

ON that same entry .. i removed one Matrix block.. 

And then again. .. 
![Snag_1a22ed71](https://user-images.githubusercontent.com/76176291/198519606-401a9eff-43ba-45cc-8c7a-fb61929f92ab.png)


Now getting all the time..

If i put back that matrix block i deleted.. 
then its OK:: no error..

**Comment by wmdhosting** [comment]
Found this one .. too. 
![Snag_a9532de](https://user-images.githubusercontent.com/76176291/198940720-3b3f12d1-a2be-44ca-9f27-ba95993bbfa7.png)

**Comment by ryssbowh** [comment]
I've moved this one to its own issue : https://github.com/ryssbowh/craft-activity/issues/3

**Comment by ryssbowh** [comment]
Regarding the matrix issue, can you describe exactly what you're doing, step by step. I really can't reproduce this

**Comment by wmdhosting** [comment]
I have entry.. 

With multiple. matrix blocks..  

Here i have  2 matrix block that  generate..  entries.. list.. 

when more than 1 . then no error. 
when only 1.  error.. 
 
 Does that help :)

**Comment by ryssbowh** [comment]
Not really, I'm guessing you're removing blocks/fields in the matrix ? Tried everything I could but can't replicate.
I've changed something in 2.2.0, it should fix this.

**Comment by wmdhosting** [comment]
this seems OK now.. ... 

Just there is new one now.. .. 

SAVING MATRIX FIELD::   even without changes,. 
![Snag_7068ab2](https://user-images.githubusercontent.com/76176291/199989806-4508d111-ea00-4d2a-adec-a2c4564efd8f.png)

**Comment by ryssbowh** [comment]
You get this when saving a Matrix field ?
This class is used for options for fields like Dropdown, would be interested to have the full backtrace from your logs if you can find it.
This is fixed in 2.2.2.

**Comment by wmdhosting** [comment]
Still getting error...  just on Matrix..  Field save.. 
Few screens if can help.. 
![Snag_ea89f63](https://user-images.githubusercontent.com/76176291/202166265-a8794a5f-ff5f-48f5-aa21-4dc364915237.png)
![Snag_ea8ad1e](https://user-images.githubusercontent.com/76176291/202166278-347ff993-f108-4855-adbe-ef5eedcdedb6.png)

![Snag_ea8b9c1](https://user-images.githubusercontent.com/76176291/202166289-cdbae9c5-bcde-4ffd-9a8b-7a9e741ae46f.png)
![Snag_ea8c598](https://user-images.githubusercontent.com/76176291/202166303-e778c6f1-38da-49aa-b62e-c2674f5906cf.png)
![Snag_ea8d4bb](https://user-images.githubusercontent.com/76176291/202166327-d1db84e4-3997-4b7b-9aa4-edd66091f522.png)
![Snag_ea8e499](https://user-images.githubusercontent.com/76176291/202166340-fc4ebc71-2a7e-4a9e-a82c-4c511c4e212d.png)
![Snag_ea8f36e](https://user-images.githubusercontent.com/76176291/202166352-b121a0eb-33e2-41ff-9a6b-a8731a0d1c21.png)
![Snag_ea8fff1](https://user-images.githubusercontent.com/76176291/202166363-62ece7f9-3b6c-40d4-8c60-5d681d161fe3.png)

**Comment by ryssbowh** [comment]
Hi,
I fixed this in 2.2.4.
I'll close this as it's gotten quite far from the original issue.
Also, it would be easier for everyone if you just pasted the stacktrace from your logs instead of screenshots.
